/**
 * Regenerate the self-hosted webfont subset under `public/fonts/`.
 *
 * The stylesheet used to open with an `@import` from fonts.googleapis.com. That is a
 * render-blocking serial round trip on every cold load (fetch CSS -> discover import ->
 * fetch CSS -> fetch woff2), it fails wherever Google is unreachable, and it hands a
 * third party an IP address on every session — which is also why a packaged Steam build
 * could not have used it.
 *
 * Only the `latin` subsets are kept: the game ships English copy and the other subsets
 * are dead weight. All six faces together are ~77 kB.
 *
 *   node scripts/fetchFonts.mjs
 *
 * Then paste `public/fonts/fonts.css` over the @font-face block at the top of
 * `src/styles/app.css`. The faces live in the bundled CSS rather than behind another
 * @import so the browser discovers them in the first stylesheet it already has.
 */
import { mkdirSync, writeFileSync } from 'node:fs';

const API =
  'https://fonts.googleapis.com/css2?family=Audiowide&family=Chakra+Petch:wght@500;600;700&family=Space+Mono:wght@400;700&display=swap';

// The css2 API serves woff2 only to browser user agents; Node's default gets ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT = 'public/fonts';
const slug = (family) => family.toLowerCase().replace(/\s+/g, '-');

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();

// Each face is preceded by a `/* subset */` comment; keep the latin ones.
const blocks = css
  .split('/*')
  .slice(1)
  .map((block) => `/*${block}`)
  .filter((block) => /^\/\*\s*latin\s*\*\//.test(block));

if (blocks.length === 0) {
  console.error('No latin @font-face blocks found — did the css2 response shape change?');
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });
const faces = [];

for (const block of blocks) {
  const family = /font-family: '([^']+)'/.exec(block)?.[1];
  const weight = /font-weight: (\d+)/.exec(block)?.[1];
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
  const range = /unicode-range: ([^;]+);/.exec(block)?.[1];
  if (!family || !weight || !url || !range) {
    console.error('Unparseable @font-face block:', block.slice(0, 120));
    process.exit(1);
  }

  const file = `${slug(family)}-${weight}.woff2`;
  const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(`${OUT}/${file}`, bytes);
  console.log(`${file.padEnd(24)} ${bytes.length} bytes`);

  faces.push(
    `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n` +
      `  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n  unicode-range: ${range};\n}`,
  );
}

writeFileSync(
  `${OUT}/fonts.css`,
  '/* Generated by scripts/fetchFonts.mjs — do not hand-edit. */\n' + faces.join('\n') + '\n',
);
console.log(`\nwrote ${OUT}/fonts.css (${faces.length} faces)`);
